# Generated by Django 5.0.4 on 2024-04-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alt',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
