# Generated by Django 5.0.4 on 2024-04-22 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
